### ISSUE TITLE
VGUI2 Scoreboard TODO list

### ISSUE THREAD

**Issue by tmp64** [tmp64/BugfixedHL#2]
- [x] Add a label to spectators
- [x] Mark muted players with icons (on top of avatars or in a separate column like in the original scoreboard)
- [x] Allow server to change team scores as it is done in the original scoreboard

**Comment by abdobiskra** [comment]
Hi 
there bug in spectator list : 
https://imgur.com/a/oXiAk4f

**Comment by tmp64** [comment]
@abdobiskra I've opened #3 regarding sprites in HUD.
It would be nice if you said how to reproduce the spectator bug in issue #4
I will check colors in names later.

**Comment by abdobiskra** [comment]
> It would be nice if you said how to reproduce the spectator bug in issue #4
I am not good at explaining .. xD
But I am using the server system rounds (i used natives like hl_user_spawn() & hl_get_user_spectator() ... set_user_team() .. etc )
I leave you a demo to help you understand?
[debug_demo.zip](https://github.com/tmp64/BugfixedHL/files/2538661/debug_demo.zip)
or here ip of server : 173.249.21.128:27018

**Comment by Safety1st** [comment]
Please add the ability to hide spectator labels from regular players. It's needed to hide spectating admins.

**Comment by tmp64** [comment]
That should be done on the server-side.

There are two ways a client can know that some player is spectating.

First is via "Spectator" message. It is sent when player is connecting to the server and when someone begins/ends spectating.
This message is also sent in *hl.inc* AMXX include.
https://github.com/tmp64/BugfixedHL/blob/c2606b3a0804d107b8a08248eac2ff82cb6c5bfd/dlls/player.cpp#L4114-L4126
https://github.com/tmp64/BugfixedHL/blob/c2606b3a0804d107b8a08248eac2ff82cb6c5bfd/dlls/observer.cpp#L109-L113
https://github.com/tmp64/BugfixedHL/blob/c2606b3a0804d107b8a08248eac2ff82cb6c5bfd/dlls/observer.cpp#L128-L132



Second is using an obscure "feature" in team info. Every player has a team name and a team number (even in DM mode, in that case number is 0 and name is "Players"). But spectators have an empty team name.
https://github.com/tmp64/BugfixedHL/blob/c2606b3a0804d107b8a08248eac2ff82cb6c5bfd/cl_dll/vgui2/CScorePanel.cpp#L312-L315
https://github.com/tmp64/BugfixedHL/blob/c2606b3a0804d107b8a08248eac2ff82cb6c5bfd/cl_dll/vgui2/CScorePanel.cpp#L376-L393
